-- Claim-safe, deterministic French content. No user account or credential is seeded.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO services
    (locale, content_key, slug, title, eyebrow, summary, problem_text, positioning_text, blocks_json, status, seo_title, seo_description, sort_order, published_at)
VALUES
    ('fr', 'expertise.data-ai', 'data-ia', 'Data & IA', 'Données fiables, décisions utiles', 'Transformer les données disponibles en décisions explicables et actionnables.', 'Des données dispersées ou peu gouvernées ralentissent les décisions et fragilisent la confiance.', 'SCTECH structure la chaîne de valeur des données, de la gouvernance aux usages analytiques et IA.', '{"version":1,"blocks":[{"type":"list","title":"Capacités","items":["Stratégie et gouvernance des données","Plateformes analytiques","Cas d’usage IA encadrés","Qualité, traçabilité et observabilité"]}]}', 'published', 'Data & IA | SCTECH', 'Gouvernance, plateformes data et usages IA encadrés pour des décisions plus fiables.', 10, UTC_TIMESTAMP(6)),
    ('fr', 'expertise.software', 'developpement-securise', 'Développement Digital Sécurisé', 'Logiciels robustes par conception', 'Concevoir et faire évoluer des produits numériques maintenables, sûrs et alignés sur les opérations.', 'Les applications critiques accumulent souvent dette technique, dépendances et risques de continuité.', 'SCTECH combine architecture, expérience utilisateur, delivery et sécurité dans un même cadre de réalisation.', '{"version":1,"blocks":[{"type":"list","title":"Capacités","items":["Architecture applicative","Produits web et métiers","API et intégration","Modernisation progressive"]}]}', 'published', 'Développement Digital Sécurisé | SCTECH', 'Architecture, développement et modernisation de logiciels métiers sécurisés.', 20, UTC_TIMESTAMP(6)),
    ('fr', 'expertise.cloud', 'cloud-devsecops', 'Cloud, Infrastructure & DevSecOps', 'Une infrastructure gouvernée', 'Construire des fondations cloud lisibles, automatisées et adaptées aux exigences de disponibilité.', 'Sans standards partagés, le cloud peut amplifier les coûts, les écarts de configuration et la complexité opérationnelle.', 'SCTECH traite architecture, automatisation, observabilité et gouvernance comme un système cohérent.', '{"version":1,"blocks":[{"type":"list","title":"Capacités","items":["Architecture cloud et hybride","Infrastructure as Code","Chaînes de livraison sécurisées","Observabilité et continuité"]}]}', 'published', 'Cloud, Infrastructure & DevSecOps | SCTECH', 'Architecture cloud, automatisation, observabilité et gouvernance des plateformes.', 30, UTC_TIMESTAMP(6)),
    ('fr', 'expertise.cybersecurity', 'cybersecurite-conformite', 'Cybersécurité & Conformité', 'Réduire le risque utilement', 'Intégrer la sécurité aux choix d’architecture, aux opérations et aux pratiques de delivery.', 'Une sécurité traitée trop tard laisse des angles morts et ralentit les équipes au moment des arbitrages.', 'SCTECH aide à prioriser les risques et à inscrire les contrôles dans le fonctionnement quotidien.', '{"version":1,"blocks":[{"type":"list","title":"Capacités","items":["Évaluation et feuille de route","Sécurité applicative et cloud","Tests d’intrusion cadrés","Accompagnement des démarches de conformité"]}]}', 'published', 'Cybersécurité & Conformité | SCTECH', 'Stratégie, architecture et pratiques de cybersécurité orientées risque.', 40, UTC_TIMESTAMP(6)),
    ('fr', 'expertise.transformation', 'transformation-digitale', 'Conseil & Transformation Digitale', 'Du cap à l’adoption', 'Orchestrer les choix technologiques, les processus et l’adoption autour d’objectifs opérationnels clairs.', 'Multiplier les outils sans modèle opérationnel partagé produit rarement une transformation durable.', 'SCTECH relie diagnostic, priorisation, réalisation et accompagnement du changement.', '{"version":1,"blocks":[{"type":"list","title":"Capacités","items":["Diagnostic et trajectoire","Design de services","Pilotage de portefeuille","Adoption et transfert de compétences"]}]}', 'published', 'Conseil & Transformation Digitale | SCTECH', 'Stratégie, design de services et exécution d’une transformation numérique maîtrisée.', 50, UTC_TIMESTAMP(6)),
    ('fr', 'expertise.nearshoring', 'nearshoring', 'Nearshoring & Équipes dédiées', 'Une équipe qui s’intègre vraiment', 'Renforcer une capacité produit ou d’ingénierie avec un cadre de collaboration explicite entre le Maroc et l’Europe.', 'Un renfort externe mal intégré fragmente la responsabilité, la connaissance et la qualité de livraison.', 'SCTECH structure gouvernance, qualité, sécurité, documentation et transfert pour préserver la continuité.', '{"version":1,"blocks":[{"type":"list","title":"Capacités","items":["Équipes dédiées","Renfort de compétences","Gouvernance de delivery","Transfert de connaissance"]}]}', 'published', 'Nearshoring & équipes dédiées | SCTECH', 'Équipes dédiées et delivery nearshore entre le Maroc et l’Europe.', 60, UTC_TIMESTAMP(6))
ON DUPLICATE KEY UPDATE
    slug = VALUES(slug), title = VALUES(title), summary = VALUES(summary), problem_text = VALUES(problem_text),
    positioning_text = VALUES(positioning_text), blocks_json = VALUES(blocks_json),
    seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), sort_order = VALUES(sort_order);

INSERT INTO sectors
    (locale, content_key, slug, title, eyebrow, summary, blocks_json, status, seo_title, seo_description, sort_order, published_at)
VALUES
    ('fr', 'sector.finance', 'services-financiers', 'Services financiers', 'Confiance et maîtrise', 'Faire évoluer les services et les plateformes dans un cadre où traçabilité, résilience et sécurité restent centrales.', '{"version":1,"blocks":[{"type":"paragraph","text":"Des architectures lisibles et des données gouvernées facilitent les arbitrages sans promettre une conformité automatique."}]}', 'published', 'Technologie pour les services financiers | SCTECH', 'Data, logiciel, cloud et cybersécurité pour les organisations de services financiers.', 10, UTC_TIMESTAMP(6)),
    ('fr', 'sector.enterprise', 'pme-entreprises', 'PME & entreprises', 'Moderniser avec continuité', 'Relier produits, données et opérations afin de faire évoluer les outils sans déstabiliser l’activité.', '{"version":1,"blocks":[{"type":"paragraph","text":"La trajectoire privilégie les dépendances critiques, l’adoption et la capacité des équipes à exploiter le changement."}]}', 'published', 'Technologie pour les PME et entreprises | SCTECH', 'Data, logiciels, cloud et sécurité pour les PME et entreprises.', 20, UTC_TIMESTAMP(6)),
    ('fr', 'sector.ecommerce', 'ecommerce', 'E-commerce', 'Parcours et opérations cohérents', 'Unifier parcours, données et opérations pour fiabiliser les flux commerciaux et leur évolution.', '{"version":1,"blocks":[{"type":"paragraph","text":"La valeur vient de la cohérence entre expérience client, systèmes internes, intégrations et mesure utile."}]}', 'published', 'Technologie pour l’e-commerce | SCTECH', 'Produits numériques, données et intégrations sécurisées pour l’e-commerce.', 30, UTC_TIMESTAMP(6)),
    ('fr', 'sector.energy', 'energie', 'Énergie', 'Continuité et maîtrise des flux', 'Relier données, systèmes métiers et opérations pour soutenir une transformation progressive et résiliente.', '{"version":1,"blocks":[{"type":"paragraph","text":"La modernisation privilégie l’interopérabilité, la continuité d’activité et la sécurité des flux."}]}', 'published', 'Technologie pour l’énergie | SCTECH', 'Modernisation, data et sécurité au service des opérations du secteur de l’énergie.', 40, UTC_TIMESTAMP(6))
ON DUPLICATE KEY UPDATE
    slug = VALUES(slug), title = VALUES(title), summary = VALUES(summary), blocks_json = VALUES(blocks_json),
    seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), sort_order = VALUES(sort_order);

INSERT INTO articles
    (locale, content_key, slug, title, eyebrow, summary, blocks_json, status, seo_title, seo_description, reading_minutes, published_at)
VALUES
    ('fr', 'insight.data-governance-decision', 'gouvernance-data-commencer-par-decisions', 'Gouvernance data : commencer par les décisions', 'Point de vue', 'Une gouvernance utile part des décisions à fiabiliser, puis remonte vers les données, les rôles et les contrôles nécessaires.', '{"version":1,"blocks":[{"type":"heading","level":2,"text":"Partir d’un besoin vérifiable"},{"type":"paragraph","text":"Un programme data gagne en clarté lorsqu’il nomme les décisions concernées, leurs propriétaires et les conséquences d’une information incomplète."},{"type":"heading","level":2,"text":"Installer un contrat de confiance"},{"type":"list","title":"Questions de départ","items":["Quelle décision doit être mieux informée ?","Qui répond de la définition de chaque donnée ?","Comment détecter et traiter une rupture de qualité ?","Quelle preuve de traçabilité doit rester disponible ?"]},{"type":"paragraph","text":"Ce cadre permet de prioriser sans transformer la gouvernance en catalogue de règles déconnectées des usages."}]}', 'published', 'Gouvernance data : commencer par les décisions | SCTECH', 'Une méthode pragmatique pour relier gouvernance des données, responsabilités et décisions.', 4, UTC_TIMESTAMP(6)),
    ('fr', 'insight.secure-software-continuum', 'securite-logicielle-continuum', 'La sécurité logicielle est un continuum', 'Point de vue', 'Architecture, code, déploiement et exploitation forment une même surface de risque : les contrôles doivent suivre ce continuum.', '{"version":1,"blocks":[{"type":"heading","level":2,"text":"Éviter le contrôle tardif"},{"type":"paragraph","text":"Une revue finale ne compense pas des choix d’architecture opaques, des dépendances non suivies ou des secrets mal gérés."},{"type":"heading","level":2,"text":"Créer des boucles courtes"},{"type":"list","title":"Pratiques structurantes","items":["Modéliser les menaces lors des décisions d’architecture","Automatiser les contrôles reproductibles","Traiter les alertes selon leur risque réel","Conserver des chemins de correction et de retour arrière"]},{"type":"paragraph","text":"La sécurité devient alors une propriété observable du système plutôt qu’une étape isolée du projet."}]}', 'published', 'La sécurité logicielle est un continuum | SCTECH', 'Intégrer la sécurité à l’architecture, au delivery et aux opérations logicielles.', 4, UTC_TIMESTAMP(6)),
    ('fr', 'insight.cloud-operating-model', 'cloud-modele-operationnel-avant-outils', 'Cloud : le modèle opérationnel avant les outils', 'Point de vue', 'Les choix cloud deviennent durables lorsque responsabilités, garde-fous et modes de décision sont définis avant l’accumulation de services.', '{"version":1,"blocks":[{"type":"heading","level":2,"text":"Rendre les responsabilités explicites"},{"type":"paragraph","text":"Une plateforme partagée doit préciser qui fournit les fondations, qui exploite les services et comment les écarts sont arbitrés."},{"type":"heading","level":2,"text":"Standardiser ce qui libère les équipes"},{"type":"list","title":"Fondations utiles","items":["Identités et accès par défaut","Journalisation et observabilité communes","Patrons de déploiement réutilisables","Visibilité des coûts et responsabilités"]},{"type":"paragraph","text":"Les outils viennent ensuite concrétiser ce modèle et peuvent évoluer sans remettre en cause ses principes."}]}', 'published', 'Cloud : le modèle opérationnel avant les outils | SCTECH', 'Définir responsabilités et garde-fous avant de multiplier les services cloud.', 4, UTC_TIMESTAMP(6))
ON DUPLICATE KEY UPDATE
    title = VALUES(title), summary = VALUES(summary), blocks_json = VALUES(blocks_json),
    seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), reading_minutes = VALUES(reading_minutes);

INSERT INTO case_studies
    (locale, content_key, slug, title, summary, verification_notes, blocks_json, status, sort_order)
VALUES
    ('fr', 'draft.reference-template-data', 'reference-data-a-valider', 'Brouillon interne — référence Data à valider', 'Gabarit non publiable en attente d’éléments vérifiés et d’une autorisation client.', 'Ne publier qu’après validation écrite du client, des résultats, des visuels et de chaque affirmation.', '{"version":1,"blocks":[]}', 'draft', 10),
    ('fr', 'draft.reference-template-platform', 'reference-plateforme-a-valider', 'Brouillon interne — référence Plateforme à valider', 'Gabarit non publiable en attente d’éléments vérifiés et d’une autorisation client.', 'Ne publier qu’après validation écrite du client, des résultats, des visuels et de chaque affirmation.', '{"version":1,"blocks":[]}', 'draft', 20)
ON DUPLICATE KEY UPDATE
    title = VALUES(title), summary = VALUES(summary), verification_notes = VALUES(verification_notes), status = 'draft';

INSERT INTO site_settings
    (locale, content_key, value_json, status, is_sensitive)
VALUES
    ('fr', 'contact.public', '{"email":"contact@sctech.ma","city":"Casablanca","country":"Maroc"}', 'published', 0),
    ('fr', 'legal.launch_gate', '{"complete":false,"missing":["legal_entity_name","rc","ice","if","full_address","approved_privacy_copy","retention_period","legal_review"]}', 'draft', 0),
    ('fr', 'privacy.essential_cookies', '{"analytics":false,"embeds":false,"essential":["form_session","admin_session"]}', 'published', 0)
ON DUPLICATE KEY UPDATE value_json = VALUES(value_json), status = VALUES(status), is_sensitive = VALUES(is_sensitive);
